//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Of_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string Customer_Id { get; set; }
        public string Customer_Name { get; set; }
        public Nullable<decimal> Customer_Phone { get; set; }
        public string Customer_Address { get; set; }
        public string Customer_Email { get; set; }
    }
}
