//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Of_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public string Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Password { get; set; }
        public Nullable<decimal> Employee_Phone_number { get; set; }
        public string Employee_Address { get; set; }
        public string Employee_Type { get; set; }
    }
}
