//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Of_Sales
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Product_ID { get; set; }
        public Nullable<decimal> Unit_Cost { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Supplier_Id { get; set; }
        public string Product_Name { get; set; }
        public string Product_Catagory_ID { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
